name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        cd Abgabe_4
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test 1
      run: |
        python Abgabe_4/framework/physec_praktikum.py -A Abgabe_4/Messungen/Messungen_aus_3/A.csv -B Abgabe_4/Messungen/Messungen_aus_3/B.csv -E Abgabe_4/Messungen/Messungen_aus_3/E.csv -X 1 -Q 1 --size 50 
    - name: Test 2
      run: |
        python Abgabe_4/framework/physec_praktikum.py -A Abgabe_4/Messungen/Messungen_aus_3/A.csv -B Abgabe_4/Messungen/Messungen_aus_3/B.csv -E Abgabe_4/Messungen/Messungen_aus_3/E.csv -X 2 -Q 0 --size 50 
        python Abgabe_4/framework/physec_praktikum.py -A Abgabe_4/Messungen/Messungen_aus_3/A.csv -B Abgabe_4/Messungen/Messungen_aus_3/B.csv -E Abgabe_4/Messungen/Messungen_aus_3/E.csv -X 2 -Q 1 --size 50 
        python Abgabe_4/framework/physec_praktikum.py -A Abgabe_4/Messungen/Messungen_aus_3/A.csv -B Abgabe_4/Messungen/Messungen_aus_3/B.csv -E Abgabe_4/Messungen/Messungen_aus_3/E.csv -X 2 -Q 2 --size 10 
    - name: Test 3
      run: |
        python Abgabe_4/framework/physec_praktikum.py -A Abgabe_4/Messungen/Messungen_aus_3/A.csv -B Abgabe_4/Messungen/Messungen_aus_3/B.csv -E Abgabe_4/Messungen/Messungen_aus_3/E.csv -X 3 -Q 0 --size 50 
        python Abgabe_4/framework/physec_praktikum.py -A Abgabe_4/Messungen/Messungen_aus_3/A.csv -B Abgabe_4/Messungen/Messungen_aus_3/B.csv -E Abgabe_4/Messungen/Messungen_aus_3/E.csv -X 3 -Q 1 --size 50 
        python Abgabe_4/framework/physec_praktikum.py -A Abgabe_4/Messungen/Messungen_aus_3/A.csv -B Abgabe_4/Messungen/Messungen_aus_3/B.csv -E Abgabe_4/Messungen/Messungen_aus_3/E.csv -X 3 -Q 2 --size 10 
    - name: Test 4
      run: |
        python Abgabe_4/framework/physec_praktikum.py -A Abgabe_4/Messungen/Messungen_aus_3/A.csv -B Abgabe_4/Messungen/Messungen_aus_3/B.csv -E Abgabe_4/Messungen/Messungen_aus_3/E.csv -X 4 -Q 1 --size 50 
    - name: Upload PDF 
      uses:  actions/upload-artifact@v1
      with:
        name: Messungen
        path: output_Ex4/
